#!/bin/bash

# Check if the database name is provided as an argument
if [ $# -ne 1 ]; then
    echo "Usage: $0 <database_name>"
    exit 1
fi

# Define the MongoDB database name
db_name=$1

# Run the MongoDB shell with the provided database name
mongo $db_name <<EOF
db.school.find({ "name": /^Holberton/ }).forEach(printjson)
EOF
